[project]
name = "taskflow-agent"
version = "0.1.0"
description = "Task Assigning Agent that creates and assigns tasks while listening to the conversation. Integrates into Slack for converstaion, Trello and Clickup for task creation."
authors = [
    {name = "Akhilesh Malhti",email = "akhileshmalthi2299@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "apscheduler>=3.11.0",
    "crewai>=0.105.0",
    "email-validator>=2.2.0",
    "flask>=3.1.0",
    "flask-sqlalchemy>=3.1.1",
    "gpt-index>=0.6.0",
    "groq>=0.19.0",
    "gunicorn>=23.0.0",
    "langchain>=0.3.20",
    "llama-index>=0.12.23",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.0.1",
    "slack-sdk>=3.34.0",
    "sqlalchemy>=2.0.39",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
