# [theme]
# base="dark"

# # Option 1: "Midnight Ocean"
# [theme]
# primaryColor = "#3498DB"
# backgroundColor = "#0C1A2A"
# secondaryBackgroundColor = "#1F3A4F"
# textColor = "#E0F2FE"
# font = "sans serif"

# Option 2: "Cyberpunk Dusk"
# [theme]
# primaryColor = "#FF69B4"
# backgroundColor = "#121212"
# secondaryBackgroundColor = "#282828"
# textColor = "#E0E0E0"
# font = "sans serif"

# # Option 3: "Forest Twilight"
# [theme]
# primaryColor = "#81C784"
# backgroundColor = "#1A1A1A"
# secondaryBackgroundColor = "#2E2E2E"
# textColor = "#F5F5F5"
# font = "sans serif"

# Option 4: "Modern Minimalist"
# [theme]
# primaryColor = "#64B5F6"
# backgroundColor = "#181818"
# secondaryBackgroundColor = "#2A2A2A"
# textColor = "#FFFFFF"
# font = "sans serif"

# Option 5: "Light Mode"
# [theme]
# primaryColor = "#f63366"
# backgroundColor = "#FFFFFF"
# secondaryBackgroundColor = "#f0f2f6"
# textColor = "#262730"
# font = "sans serif"

# option 6: "Electric Violet"
# [theme]
# primaryColor = "#A020F0" # Violet
# backgroundColor = "#111111" # Near-black
# secondaryBackgroundColor = "#222222" # Dark gray
# textColor = "#E6E6FA" # Lavender
# font = "monospace"

# [theme]
# primaryColor = "#10A37F" # teal-ish primary color
# backgroundColor = "#343541" # Dark gray background
# secondaryBackgroundColor = "#444654" # Slightly lighter dark gray
# textColor = "#D1D5DD" # Light gray text
# font = "sans serif"

[theme]
primaryColor = "#6633FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false